language: python
sudo: false
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
script:
  - python --version
  - python setup.py build
  - python setup.py test
  - python -m pip install setuptools twine wheel
  - python setup.py sdist bdist_wheel
  - python setup.py install
#  - for i in ./examples/*.py ; do $i ; done
